spring.application.name=search-api
# server.port=8080
server.servlet.context-path=/search-api

server.shutdown=immediate

server.error.include-message=always
server.error.include-binding-errors=always

# logging.file.name=repo.log
logging.level.root=INFO
logging.level.web=INFO
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.data=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.nl.soilwise.repo.service.ServiceRepo=INFO
# logging.level.org.apache.http=DEBUG
# logging.level.org.apache.http.wire=DEBUG


# spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.datasource.hikari.leak-detection-threshold=20000

# ********************************************
spring.profiles.active=test
# *******************************************
spring.datasource.url=jdbc:postgresql://tpostgreswenr1.cdbe.wurnet.nl:5432/test_soilwise?currentSchema=metadata&sslmode=prefer
# ********************************************
# ********************************************
spring.datasource.username=soilwise
spring.datasource.password=Brugge2503

#repo.solr.url=https://solr.soilwise-he.containers.wur.nl/solr
repo.solr.url=http://localhost:8983/solr
repo.solr.collection_v2_active=records_active
repo.solr.collection_v2_shadow=records_shadow
repo.solr.user=solr
repo.solr.password=Soilwise_solr1.

repo.cors.url=http://localhost:3002
# Different values on test- and prod-environments
repo.security.ingestion.user=repo-user
repo.security.ingestion.password=Welkom01!

grobid-server.url=http://localhost:8070/api/processFulltextDocument
tika-server.url=http://localhost:9998/rmeta/text
docling-server.url=http://localhost:5001/v1/convert/source

grobid-server.enabled=false
docling_server.enabled=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/docs
# springdoc.paths-to-exclude=/rest/solutions/search/**,/rest/solutions/{id}/{property}/**
springdoc.paths-to-exclude=/rest/**
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true