spring.application.name=search-api
server.servlet.context-path=/search-api

server.shutdown=immediate

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.root=INFO
logging.level.web=INFO
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.data=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.nl.soilwise.repo.service.ServiceRepo=INFO


spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.datasource.hikari.leak-detection-threshold=20000

# ********************************************
spring.profiles.active=test
# ********************************************
spring.datasource.url=jdbc:postgresql://
# ********************************************
# ********************************************
spring.datasource.username=
spring.datasource.password=

repo.solr.url=http://localhost:8983/solr
repo.solr.collection_v2_active=records_active
repo.solr.collection_v2_shadow=records_shadow
repo.solr.user=
repo.solr.password=

repo.cors.url=http://localhost:3002
repo.security.ingestion.user=
repo.security.ingestion.password=


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/docs
springdoc.paths-to-exclude=/rest/**
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true